language: android

sudo: required
dist: trusty
group: deprecated-2017Q4

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install ant

script:
  - bin/ci/travis/run.sh

android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

notifications:
  email:
    recipients:
      - josmoo@microsoft.com
      - v-ownibl@microsoft.com
    on_success: change
    on_failure: always
