language: android

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install ant

script:
  - bin/ci/travis/run.sh

android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

notifications:
  email:
    recipients:
      - joshua.moody@xamarin.com
      - v-ownibl@microsoft.com
    on_success: change
    on_failure: always
